// Generated by https://quicktype.io
export interface UserListDto {
  lang: null;
  id: string;
  name: string;
  email: string;
  username: string;
  avatar: null;
  roles: any[];
  registerTime: Date;
}
