/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { ApiError } from './api-error';
import { ProductCategoryDto } from './product-category-dto';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ApiResponseOfListOfProductCategoryDto */
export interface IApiResponseOfListOfProductCategoryDto {
  success?: boolean;
  data?: Array<ProductCategoryDto>;
  errors?: Array<ApiError>;
  meta?: Meta;
}

/** Class for ApiResponseOfListOfProductCategoryDto */
export class ApiResponseOfListOfProductCategoryDto implements IApiResponseOfListOfProductCategoryDto {
  success?: boolean;
  data?: Array<ProductCategoryDto>;
  errors?: Array<ApiError>;
  meta?: Meta;

  constructor(data?: IApiResponseOfListOfProductCategoryDto) {
    if (data) {
      for (let property in data) {
        if (Object.hasOwn(data,property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.success = data["success"];
    if (Array.isArray(data["data"])) {
      this.data = [] as any;
      for (let item of data["data"])
        (this.data as any).push(ProductCategoryDto.fromJS(item));
    }
    if (Array.isArray(data["errors"])) {
      this.errors = [] as any;
      for (let item of data["errors"])
        (this.errors as any).push(ApiError.fromJS(item));
    }
    this.meta = data["meta"];
  }
}

  static fromJS(data: any): ApiResponseOfListOfProductCategoryDto {
    const instance = new ApiResponseOfListOfProductCategoryDto();
    instance.init(data);
    return instance;
  }
}


