/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppLogStatsDto } from './app-log-stats-dto';
import { Meta } from './meta';
import { ApiError } from './api-error';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ApiResponseOfAppLogStatsDto */
export interface IApiResponseOfAppLogStatsDto {
  success?: boolean;
  data?: AppLogStatsDto;
  errors?: Array<ApiError>;
  meta?: Meta;
}

/** Class for ApiResponseOfAppLogStatsDto */
export class ApiResponseOfAppLogStatsDto implements IApiResponseOfAppLogStatsDto {
  success?: boolean;
  data?: AppLogStatsDto;
  errors?: Array<ApiError>;
  meta?: Meta;

  constructor(data?: IApiResponseOfAppLogStatsDto) {
    if (data) {
      for (let property in data) {
        if (Object.hasOwn(data,property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.success = data["success"];
    this.data = data["data"];
    if (Array.isArray(data["errors"])) {
      this.errors = [] as any;
      for (let item of data["errors"])
        (this.errors as any).push(ApiError.fromJS(item));
    }
    this.meta = data["meta"];
  }
}

  static fromJS(data: any): ApiResponseOfAppLogStatsDto {
    const instance = new ApiResponseOfAppLogStatsDto();
    instance.init(data);
    return instance;
  }
}


