/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProvisioningStatus } from './provisioning-status';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for CreateTenantResponse */
export interface ICreateTenantResponse {
  tenantId?: string;
  slug?: string;
  status?: string;
  provisioningStatus?: ProvisioningStatus;
  trialEndsAt?: string;
}

/** Class for CreateTenantResponse */
export class CreateTenantResponse implements ICreateTenantResponse {
  tenantId?: string;
  slug?: string;
  status?: string;
  provisioningStatus?: ProvisioningStatus;
  trialEndsAt?: string;

  constructor(data?: ICreateTenantResponse) {
    if (data) {
      for (let property in data) {
        if (Object.hasOwn(data,property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.tenantId = data["tenantId"];
    this.slug = data["slug"];
    this.status = data["status"];
    this.provisioningStatus = data["provisioningStatus"];
    this.trialEndsAt = data["trialEndsAt"];
  }
}

  static fromJS(data: any): CreateTenantResponse {
    const instance = new CreateTenantResponse();
    instance.init(data);
    return instance;
  }
}


