/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for DashboardItemDto */
export interface IDashboardItemDto {
  id?: string;
  dashboardId?: string;
  position?: string;
  componentName?: string;
  data?: string;
}

/** Class for DashboardItemDto */
export class DashboardItemDto implements IDashboardItemDto {
  id?: string;
  dashboardId?: string;
  position?: string;
  componentName?: string;
  data?: string;

  constructor(data?: IDashboardItemDto) {
    if (data) {
      for (let property in data) {
        if (Object.hasOwn(data,property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.dashboardId = data["dashboardId"];
    this.position = data["position"];
    this.componentName = data["componentName"];
    this.data = data["data"];
  }
}

  static fromJS(data: any): DashboardItemDto {
    const instance = new DashboardItemDto();
    instance.init(data);
    return instance;
  }
}


