/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for DeleteLanguageCommand */
export interface IDeleteLanguageCommand {
  culture?: string;
}

/** Class for DeleteLanguageCommand */
export class DeleteLanguageCommand implements IDeleteLanguageCommand {
  culture?: string;

  constructor(data?: IDeleteLanguageCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.culture = data["culture"];
  }
}

  static fromJS(data: any): DeleteLanguageCommand {
    const instance = new DeleteLanguageCommand();
    instance.init(data);
    return instance;
  }
}


