/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum LogLevel {

    Trace = 0,

    Debug = 1,

    Information = 2,

    Warning = 3,

    Error = 4,

    Critical = 5,

    None = 6
}

