/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum LogLevelMask {

    None = 0,

    Trace = 1,

    Debug = 2,

    Information = 4,

    Warning = 8,

    Error = 16,

    Critical = 32,

    All = 63
}

