/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationPeriorityEnum } from './notification-periority-enum';
import { NotificationTypeEnum } from './notification-type-enum';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for NotificationDto */
export interface INotificationDto {
  id?: string;
  title: string;
  content?: string;
  periority?: NotificationPeriorityEnum;
  type?: NotificationTypeEnum;
  recieverUserId?: string;
  recieverName?: string;
  senderUserId?: string;
  senderName?: string;
  read?: boolean;
  data?: string;
  creationTime?: string;
}

/** Class for NotificationDto */
export class NotificationDto implements INotificationDto {
  id?: string;
  title!: string;
  content?: string;
  periority?: NotificationPeriorityEnum;
  type?: NotificationTypeEnum;
  recieverUserId?: string;
  recieverName?: string;
  senderUserId?: string;
  senderName?: string;
  read?: boolean;
  data?: string;
  creationTime?: string;

  constructor(data?: INotificationDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.title = data["title"];
    this.content = data["content"];
    this.periority = data["periority"];
    this.type = data["type"];
    this.recieverUserId = data["recieverUserId"];
    this.recieverName = data["recieverName"];
    this.senderUserId = data["senderUserId"];
    this.senderName = data["senderName"];
    this.read = data["read"];
    this.data = data["data"];
    this.creationTime = data["creationTime"];
  }
}

  static fromJS(data: any): NotificationDto {
    const instance = new NotificationDto();
    instance.init(data);
    return instance;
  }
}


