/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum PriceTypeEnum {

    Reqular = 0,

    WholeSale = 1,

    Discounted = 2,

    FlashSale = 3
}

