/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for SetFolderIconCommand */
export interface ISetFolderIconCommand {
  id?: string;
  icon: string;
}

/** Class for SetFolderIconCommand */
export class SetFolderIconCommand implements ISetFolderIconCommand {
  id?: string;
  icon!: string;

  constructor(data?: ISetFolderIconCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.icon = data["icon"];
  }
}

  static fromJS(data: any): SetFolderIconCommand {
    const instance = new SetFolderIconCommand();
    instance.init(data);
    return instance;
  }
}


