/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum TenantStatus {

    Pending = 1,

    Active = 2,

    Suspended = 3,

    Cancelled = 4,

    Deleted = -1
}

