/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for TenantUserDTO */
export interface ITenantUserDTO {
  id: string;
  userName: string;
  fullName?: string;
  email?: string;
  roles?: Array<string>;
}

/** Class for TenantUserDTO */
export class TenantUserDTO implements ITenantUserDTO {
  id!: string;
  userName!: string;
  fullName?: string;
  email?: string;
  roles?: Array<string>;

  constructor(data?: ITenantUserDTO) {
    if (data) {
      for (let property in data) {
        if (Object.hasOwn(data,property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.userName = data["userName"];
    this.fullName = data["fullName"];
    this.email = data["email"];
    if (Array.isArray(data["roles"])) {
      this.roles = [] as any;
      for (let item of data["roles"])
        (this.roles as any).push(item);
    }
  }
}

  static fromJS(data: any): TenantUserDTO {
    const instance = new TenantUserDTO();
    instance.init(data);
    return instance;
  }
}


