/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ActivateTenantCommand */
export interface IActivateTenantCommand {
  id: string;
  description: string;
}

/** Class for ActivateTenantCommand */
export class ActivateTenantCommand implements IActivateTenantCommand {
  id!: string;
  description!: string;

  constructor(data?: IActivateTenantCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.description = data["description"];
  }
}

  static fromJS(data: any): ActivateTenantCommand {
    const instance = new ActivateTenantCommand();
    instance.init(data);
    return instance;
  }
}


