/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { LocalizationKeyDTO } from './localization-key-dto';
import { ApiError } from './api-error';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ApiResponseOfListOfLocalizationKeyDTO */
export interface IApiResponseOfListOfLocalizationKeyDTO {
  success?: boolean;
  data?: Array<LocalizationKeyDTO>;
  errors?: Array<ApiError>;
  meta?: Meta;
}

/** Class for ApiResponseOfListOfLocalizationKeyDTO */
export class ApiResponseOfListOfLocalizationKeyDTO implements IApiResponseOfListOfLocalizationKeyDTO {
  success?: boolean;
  data?: Array<LocalizationKeyDTO>;
  errors?: Array<ApiError>;
  meta?: Meta;

  constructor(data?: IApiResponseOfListOfLocalizationKeyDTO) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.success = data["success"];
    if (Array.isArray(data["data"])) {
      this.data = [] as any;
      for (let item of data["data"])
        (this.data as any).push(LocalizationKeyDTO.fromJS(item));
    }
    if (Array.isArray(data["errors"])) {
      this.errors = [] as any;
      for (let item of data["errors"])
        (this.errors as any).push(ApiError.fromJS(item));
    }
    this.meta = data["meta"];
  }
}

  static fromJS(data: any): ApiResponseOfListOfLocalizationKeyDTO {
    const instance = new ApiResponseOfListOfLocalizationKeyDTO();
    instance.init(data);
    return instance;
  }
}


