/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { LastLoginDto } from './last-login-dto';
import { ApiError } from './api-error';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ApiResponseOfListOfLastLoginDto */
export interface IApiResponseOfListOfLastLoginDto {
  success?: boolean;
  data?: Array<LastLoginDto>;
  errors?: Array<ApiError>;
  meta?: Meta;
}

/** Class for ApiResponseOfListOfLastLoginDto */
export class ApiResponseOfListOfLastLoginDto implements IApiResponseOfListOfLastLoginDto {
  success?: boolean;
  data?: Array<LastLoginDto>;
  errors?: Array<ApiError>;
  meta?: Meta;

  constructor(data?: IApiResponseOfListOfLastLoginDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.success = data["success"];
    if (Array.isArray(data["data"])) {
      this.data = [] as any;
      for (let item of data["data"])
        (this.data as any).push(LastLoginDto.fromJS(item));
    }
    if (Array.isArray(data["errors"])) {
      this.errors = [] as any;
      for (let item of data["errors"])
        (this.errors as any).push(ApiError.fromJS(item));
    }
    this.meta = data["meta"];
  }
}

  static fromJS(data: any): ApiResponseOfListOfLastLoginDto {
    const instance = new ApiResponseOfListOfLastLoginDto();
    instance.init(data);
    return instance;
  }
}


