/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for CacheEntryDto */
export interface ICacheEntryDto {
  key?: string;
  provider?: string;
  lastModified?: string;
  expiration?: string;
  sizeInBytes?: number;
}

/** Class for CacheEntryDto */
export class CacheEntryDto implements ICacheEntryDto {
  key?: string;
  provider?: string;
  lastModified?: string;
  expiration?: string;
  sizeInBytes?: number;

  constructor(data?: ICacheEntryDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.key = data["key"];
    this.provider = data["provider"];
    this.lastModified = data["lastModified"];
    this.expiration = data["expiration"];
    this.sizeInBytes = data["sizeInBytes"];
  }
}

  static fromJS(data: any): CacheEntryDto {
    const instance = new CacheEntryDto();
    instance.init(data);
    return instance;
  }
}


