/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for CaptchaDTO */
export interface ICaptchaDTO {
  key: string;
  img: string;
  sensitive: boolean;
}

/** Class for CaptchaDTO */
export class CaptchaDTO implements ICaptchaDTO {
  key!: string;
  img!: string;
  sensitive!: boolean;

  constructor(data?: ICaptchaDTO) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.key = data["key"];
    this.img = data["img"];
    this.sensitive = data["sensitive"];
  }
}

  static fromJS(data: any): CaptchaDTO {
    const instance = new CaptchaDTO();
    instance.init(data);
    return instance;
  }
}


