/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for ChangeActiveMenuCommand */
export interface IChangeActiveMenuCommand {
  id?: string;
  isActive?: boolean;
}

/** Class for ChangeActiveMenuCommand */
export class ChangeActiveMenuCommand implements IChangeActiveMenuCommand {
  id?: string;
  isActive?: boolean;

  constructor(data?: IChangeActiveMenuCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.isActive = data["isActive"];
  }
}

  static fromJS(data: any): ChangeActiveMenuCommand {
    const instance = new ChangeActiveMenuCommand();
    instance.init(data);
    return instance;
  }
}


