/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardItemDto } from './dashboard-item-dto';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for CreateOrUpdateDashboardCommand */
export interface ICreateOrUpdateDashboardCommand {
  id?: string;
  userId?: string;
  title: string;
  order?: number;
  isPublic?: boolean;
  dashboardItems?: Array<DashboardItemDto>;
}

/** Class for CreateOrUpdateDashboardCommand */
export class CreateOrUpdateDashboardCommand implements ICreateOrUpdateDashboardCommand {
  id?: string;
  userId?: string;
  title!: string;
  order?: number;
  isPublic?: boolean;
  dashboardItems?: Array<DashboardItemDto>;

  constructor(data?: ICreateOrUpdateDashboardCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.userId = data["userId"];
    this.title = data["title"];
    this.order = data["order"];
    this.isPublic = data["isPublic"];
    if (Array.isArray(data["dashboardItems"])) {
      this.dashboardItems = [] as any;
      for (let item of data["dashboardItems"])
        (this.dashboardItems as any).push(DashboardItemDto.fromJS(item));
    }
  }
}

  static fromJS(data: any): CreateOrUpdateDashboardCommand {
    const instance = new CreateOrUpdateDashboardCommand();
    instance.init(data);
    return instance;
  }
}


