/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DatabaseStrategy } from './database-strategy';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for CreateTenantCommand */
export interface ICreateTenantCommand {
  name: string;
  slug: string;
  legalName?: string;
  registrationNumber?: string;
  taxId?: string;
  email: string;
  phone?: string;
  mobile?: string;
  website?: string;
  country: string;
  city: string;
  address?: string;
  postalCode?: string;
  latitude?: number;
  longitude?: number;
  databaseStrategy?: DatabaseStrategy;
  adminFirstName: string;
  adminLastName: string;
  adminEmail: string;
  adminUserName: string;
  adminPassword: string;
  adminMobile: string;
  subscriptionPlan?: string;
  maxUsers?: number;
  maxStorageMB?: number;
  isTrial?: boolean;
  trialDays?: number;
  logoUrl?: string;
  primaryColor?: string;
  secondaryColor?: string;
  require2FA?: boolean;
  sessionTimeoutMinutes?: number;
  passwordMinLength?: number;
  passwordRequireSpecialChar?: boolean;
  allowedIpAddresses?: Array<string>;
  featureFlags?: { [key: string]: boolean; };
}

/** Class for CreateTenantCommand */
export class CreateTenantCommand implements ICreateTenantCommand {
  name!: string;
  slug!: string;
  legalName?: string;
  registrationNumber?: string;
  taxId?: string;
  email!: string;
  phone?: string;
  mobile?: string;
  website?: string;
  country!: string;
  city!: string;
  address?: string;
  postalCode?: string;
  latitude?: number;
  longitude?: number;
  databaseStrategy?: DatabaseStrategy;
  adminFirstName!: string;
  adminLastName!: string;
  adminEmail!: string;
  adminUserName!: string;
  adminPassword!: string;
  adminMobile!: string;
  subscriptionPlan?: string;
  maxUsers?: number;
  maxStorageMB?: number;
  isTrial?: boolean;
  trialDays?: number;
  logoUrl?: string;
  primaryColor?: string;
  secondaryColor?: string;
  require2FA?: boolean;
  sessionTimeoutMinutes?: number;
  passwordMinLength?: number;
  passwordRequireSpecialChar?: boolean;
  allowedIpAddresses?: Array<string>;
  featureFlags?: { [key: string]: boolean; };

  constructor(data?: ICreateTenantCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.name = data["name"];
    this.slug = data["slug"];
    this.legalName = data["legalName"];
    this.registrationNumber = data["registrationNumber"];
    this.taxId = data["taxId"];
    this.email = data["email"];
    this.phone = data["phone"];
    this.mobile = data["mobile"];
    this.website = data["website"];
    this.country = data["country"];
    this.city = data["city"];
    this.address = data["address"];
    this.postalCode = data["postalCode"];
    this.latitude = data["latitude"];
    this.longitude = data["longitude"];
    this.databaseStrategy = data["databaseStrategy"];
    this.adminFirstName = data["adminFirstName"];
    this.adminLastName = data["adminLastName"];
    this.adminEmail = data["adminEmail"];
    this.adminUserName = data["adminUserName"];
    this.adminPassword = data["adminPassword"];
    this.adminMobile = data["adminMobile"];
    this.subscriptionPlan = data["subscriptionPlan"];
    this.maxUsers = data["maxUsers"];
    this.maxStorageMB = data["maxStorageMB"];
    this.isTrial = data["isTrial"];
    this.trialDays = data["trialDays"];
    this.logoUrl = data["logoUrl"];
    this.primaryColor = data["primaryColor"];
    this.secondaryColor = data["secondaryColor"];
    this.require2FA = data["require2FA"];
    this.sessionTimeoutMinutes = data["sessionTimeoutMinutes"];
    this.passwordMinLength = data["passwordMinLength"];
    this.passwordRequireSpecialChar = data["passwordRequireSpecialChar"];
    if (Array.isArray(data["allowedIpAddresses"])) {
      this.allowedIpAddresses = [] as any;
      for (let item of data["allowedIpAddresses"])
        (this.allowedIpAddresses as any).push(item);
    }
    this.featureFlags = data["featureFlags"];
  }
}

  static fromJS(data: any): CreateTenantCommand {
    const instance = new CreateTenantCommand();
    instance.init(data);
    return instance;
  }
}


