/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageStatusEnum } from './page-status-enum';


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for CreatePageCommand */
export interface ICreatePageCommand {
  slag?: string;
  coverImage?: string;
  status?: PageStatusEnum;
  culture?: string;
  title?: string;
  _abstract?: string;
  description?: string;
  html?: string;
  styles?: string;
  scripts?: string;
  createdBy?: string;
}

/** Class for CreatePageCommand */
export class CreatePageCommand implements ICreatePageCommand {
  slag?: string;
  coverImage?: string;
  status?: PageStatusEnum;
  culture?: string;
  title?: string;
  _abstract?: string;
  description?: string;
  html?: string;
  styles?: string;
  scripts?: string;
  createdBy?: string;

  constructor(data?: ICreatePageCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.slag = data["slag"];
    this.coverImage = data["coverImage"];
    this.status = data["status"];
    this.culture = data["culture"];
    this.title = data["title"];
    this._abstract = data["abstract"];
    this.description = data["description"];
    this.html = data["html"];
    this.styles = data["styles"];
    this.scripts = data["scripts"];
    this.createdBy = data["createdBy"];
  }
}

  static fromJS(data: any): CreatePageCommand {
    const instance = new CreatePageCommand();
    instance.init(data);
    return instance;
  }
}


