/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for CreateUserCommand */
export interface ICreateUserCommand {
  firstName: string;
  lastName: string;
  userName: string;
  email: string;
  phoneNumber: string;
  lang: string;
  password: string;
  confirmationPassword: string;
  roles: Array<string>;
}

/** Class for CreateUserCommand */
export class CreateUserCommand implements ICreateUserCommand {
  firstName!: string;
  lastName!: string;
  userName!: string;
  email!: string;
  phoneNumber!: string;
  lang!: string;
  password!: string;
  confirmationPassword!: string;
  roles!: Array<string>;

  constructor(data?: ICreateUserCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.firstName = data["firstName"];
    this.lastName = data["lastName"];
    this.userName = data["userName"];
    this.email = data["email"];
    this.phoneNumber = data["phoneNumber"];
    this.lang = data["lang"];
    this.password = data["password"];
    this.confirmationPassword = data["confirmationPassword"];
    if (Array.isArray(data["roles"])) {
      this.roles = [] as any;
      for (let item of data["roles"])
        (this.roles as any).push(item);
    }
  }
}

  static fromJS(data: any): CreateUserCommand {
    const instance = new CreateUserCommand();
    instance.init(data);
    return instance;
  }
}


