/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalProviderTypeEnum } from './external-provider-type-enum';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for CreateExternalProviderDto */
export interface ICreateExternalProviderDto {
  name?: string;
  displayName?: string;
  scheme?: string;
  providerType?: ExternalProviderTypeEnum;
  clientId?: string;
  clientSecret?: string;
  authorizationEndpoint?: string;
  tokenEndpoint?: string;
  userInfoEndpoint?: string;
  callbackPath?: string;
  logoutEndpoint?: string;
  metadataJson?: string;
  scopes?: string;
  responseType?: string;
  responseMode?: string;
  usePkce?: boolean;
}

/** Class for CreateExternalProviderDto */
export class CreateExternalProviderDto implements ICreateExternalProviderDto {
  name?: string;
  displayName?: string;
  scheme?: string;
  providerType?: ExternalProviderTypeEnum;
  clientId?: string;
  clientSecret?: string;
  authorizationEndpoint?: string;
  tokenEndpoint?: string;
  userInfoEndpoint?: string;
  callbackPath?: string;
  logoutEndpoint?: string;
  metadataJson?: string;
  scopes?: string;
  responseType?: string;
  responseMode?: string;
  usePkce?: boolean;

  constructor(data?: ICreateExternalProviderDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.name = data["name"];
    this.displayName = data["displayName"];
    this.scheme = data["scheme"];
    this.providerType = data["providerType"];
    this.clientId = data["clientId"];
    this.clientSecret = data["clientSecret"];
    this.authorizationEndpoint = data["authorizationEndpoint"];
    this.tokenEndpoint = data["tokenEndpoint"];
    this.userInfoEndpoint = data["userInfoEndpoint"];
    this.callbackPath = data["callbackPath"];
    this.logoutEndpoint = data["logoutEndpoint"];
    this.metadataJson = data["metadataJson"];
    this.scopes = data["scopes"];
    this.responseType = data["responseType"];
    this.responseMode = data["responseMode"];
    this.usePkce = data["usePkce"];
  }
}

  static fromJS(data: any): CreateExternalProviderDto {
    const instance = new CreateExternalProviderDto();
    instance.init(data);
    return instance;
  }
}


