/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for CreateFolderCommand */
export interface ICreateFolderCommand {
  name?: string;
  isPublic?: boolean;
  parentId?: string;
}

/** Class for CreateFolderCommand */
export class CreateFolderCommand implements ICreateFolderCommand {
  name?: string;
  isPublic?: boolean;
  parentId?: string;

  constructor(data?: ICreateFolderCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.name = data["name"];
    this.isPublic = data["isPublic"];
    this.parentId = data["parentId"];
  }
}

  static fromJS(data: any): CreateFolderCommand {
    const instance = new CreateFolderCommand();
    instance.init(data);
    return instance;
  }
}


