/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { ApiError } from './api-error';
import { DashboardItemDto } from './dashboard-item-dto';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for DashboardItemDtoListApiResponse */
export interface IDashboardItemDtoListApiResponse {
  success?: boolean;
  data?: Array<DashboardItemDto>;
  errors?: Array<ApiError>;
  meta?: Meta;
}

/** Class for DashboardItemDtoListApiResponse */
export class DashboardItemDtoListApiResponse implements IDashboardItemDtoListApiResponse {
  success?: boolean;
  data?: Array<DashboardItemDto>;
  errors?: Array<ApiError>;
  meta?: Meta;

  constructor(data?: IDashboardItemDtoListApiResponse) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.success = data["success"];
    if (Array.isArray(data["data"])) {
      this.data = [] as any;
      for (let item of data["data"])
        (this.data as any).push(DashboardItemDto.fromJS(item));
    }
    if (Array.isArray(data["errors"])) {
      this.errors = [] as any;
      for (let item of data["errors"])
        (this.errors as any).push(ApiError.fromJS(item));
    }
    this.meta = data["meta"];
  }
}

  static fromJS(data: any): DashboardItemDtoListApiResponse {
    const instance = new DashboardItemDtoListApiResponse();
    instance.init(data);
    return instance;
  }
}


