/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for DeleteProductAttributeCommand */
export interface IDeleteProductAttributeCommand {
  id?: string;
}

/** Class for DeleteProductAttributeCommand */
export class DeleteProductAttributeCommand implements IDeleteProductAttributeCommand {
  id?: string;

  constructor(data?: IDeleteProductAttributeCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
  }
}

  static fromJS(data: any): DeleteProductAttributeCommand {
    const instance = new DeleteProductAttributeCommand();
    instance.init(data);
    return instance;
  }
}


