/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for EditUserCommand */
export interface IEditUserCommand {
  id?: string;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  lang: string;
  address?: string;
  roles: Array<string>;
}

/** Class for EditUserCommand */
export class EditUserCommand implements IEditUserCommand {
  id?: string;
  firstName!: string;
  lastName!: string;
  email!: string;
  phoneNumber!: string;
  lang!: string;
  address?: string;
  roles!: Array<string>;

  constructor(data?: IEditUserCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.firstName = data["firstName"];
    this.lastName = data["lastName"];
    this.email = data["email"];
    this.phoneNumber = data["phoneNumber"];
    this.lang = data["lang"];
    this.address = data["address"];
    if (Array.isArray(data["roles"])) {
      this.roles = [] as any;
      for (let item of data["roles"])
        (this.roles as any).push(item);
    }
  }
}

  static fromJS(data: any): EditUserCommand {
    const instance = new EditUserCommand();
    instance.init(data);
    return instance;
  }
}


