/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ExportAllLocalizationValueDto */
export interface IExportAllLocalizationValueDto {
  id?: string;
  title?: string;
  description?: string;
}

/** Class for ExportAllLocalizationValueDto */
export class ExportAllLocalizationValueDto implements IExportAllLocalizationValueDto {
  id?: string;
  title?: string;
  description?: string;

  constructor(data?: IExportAllLocalizationValueDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.title = data["title"];
    this.description = data["description"];
  }
}

  static fromJS(data: any): ExportAllLocalizationValueDto {
    const instance = new ExportAllLocalizationValueDto();
    instance.init(data);
    return instance;
  }
}


