/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for FileNodeDto */
export interface IFileNodeDto {
  name?: string;
  fullPath?: string;
  isFolder?: boolean;
  children?: Array<FileNodeDto>;
}

/** Class for FileNodeDto */
export class FileNodeDto implements IFileNodeDto {
  name?: string;
  fullPath?: string;
  isFolder?: boolean;
  children?: Array<FileNodeDto>;

  constructor(data?: IFileNodeDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.name = data["name"];
    this.fullPath = data["fullPath"];
    this.isFolder = data["isFolder"];
    if (Array.isArray(data["children"])) {
      this.children = [] as any;
      for (let item of data["children"])
        (this.children as any).push(FileNodeDto.fromJS(item));
    }
  }
}

  static fromJS(data: any): FileNodeDto {
    const instance = new FileNodeDto();
    instance.init(data);
    return instance;
  }
}


