/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for Generate2FARequest */
export interface IGenerate2FARequest {
  email?: string;
}

/** Class for Generate2FARequest */
export class Generate2FARequest implements IGenerate2FARequest {
  email?: string;

  constructor(data?: IGenerate2FARequest) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.email = data["email"];
  }
}

  static fromJS(data: any): Generate2FARequest {
    const instance = new Generate2FARequest();
    instance.init(data);
    return instance;
  }
}


