/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageTypeEnum } from './page-type-enum';
import { PageStatusEnum } from './page-status-enum';


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for GetFilteredPagesQuery */
export interface IGetFilteredPagesQuery {
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;
  type: PageTypeEnum;
  title?: string;
  _abstract?: string;
  authorName?: string;
  fromDate?: string;
  toDate?: string;
  status?: PageStatusEnum;
}

/** Class for GetFilteredPagesQuery */
export class GetFilteredPagesQuery implements IGetFilteredPagesQuery {
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;
  type!: PageTypeEnum;
  title?: string;
  _abstract?: string;
  authorName?: string;
  fromDate?: string;
  toDate?: string;
  status?: PageStatusEnum;

  constructor(data?: IGetFilteredPagesQuery) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.pageNumber = data["pageNumber"];
    this.pageSize = data["pageSize"];
    this.sortBy = data["sortBy"];
    this.sortDirection = data["sortDirection"];
    this.type = data["type"];
    this.title = data["title"];
    this._abstract = data["abstract"];
    this.authorName = data["authorName"];
    this.fromDate = data["fromDate"];
    this.toDate = data["toDate"];
    this.status = data["status"];
  }
}

  static fromJS(data: any): GetFilteredPagesQuery {
    const instance = new GetFilteredPagesQuery();
    instance.init(data);
    return instance;
  }
}


