/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetUserQuery { 
    PageNumber?: number;
    PageSize?: number;
    SortBy?: string | null;
    SortDirection?: string | null;
    Filter?: string | null;
}

