/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for GetProductCategoriesQuerySkip */
export interface IGetProductCategoriesQuerySkip {
}

/** Class for GetProductCategoriesQuerySkip */
export class GetProductCategoriesQuerySkip implements IGetProductCategoriesQuerySkip {

  constructor(data?: IGetProductCategoriesQuerySkip) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
  }
}

  static fromJS(data: any): GetProductCategoriesQuerySkip {
    const instance = new GetProductCategoriesQuerySkip();
    instance.init(data);
    return instance;
  }
}


