/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for GetUserQuery */
export interface IGetUserQuery {
  filter?: string;
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;
}

/** Class for GetUserQuery */
export class GetUserQuery implements IGetUserQuery {
  filter?: string;
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;

  constructor(data?: IGetUserQuery) {
    if (data) {
      for (let property in data) {
        if (Object.hasOwn(data,property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.filter = data["filter"];
    this.pageNumber = data["pageNumber"];
    this.pageSize = data["pageSize"];
    this.sortBy = data["sortBy"];
    this.sortDirection = data["sortDirection"];
  }
}

  static fromJS(data: any): GetUserQuery {
    const instance = new GetUserQuery();
    instance.init(data);
    return instance;
  }
}


