/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for GetProductsQuery */
export interface IGetProductsQuery {
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;
  filter?: string;
  categoryId?: string;
  productTypeId?: string;
}

/** Class for GetProductsQuery */
export class GetProductsQuery implements IGetProductsQuery {
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;
  filter?: string;
  categoryId?: string;
  productTypeId?: string;

  constructor(data?: IGetProductsQuery) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.pageNumber = data["pageNumber"];
    this.pageSize = data["pageSize"];
    this.sortBy = data["sortBy"];
    this.sortDirection = data["sortDirection"];
    this.filter = data["filter"];
    this.categoryId = data["categoryId"];
    this.productTypeId = data["productTypeId"];
  }
}

  static fromJS(data: any): GetProductsQuery {
    const instance = new GetProductsQuery();
    instance.init(data);
    return instance;
  }
}


