/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for GetAllPlanFeatureForEditQuery */
export interface IGetAllPlanFeatureForEditQuery {
  planId?: string;
}

/** Class for GetAllPlanFeatureForEditQuery */
export class GetAllPlanFeatureForEditQuery implements IGetAllPlanFeatureForEditQuery {
  planId?: string;

  constructor(data?: IGetAllPlanFeatureForEditQuery) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.planId = data["planId"];
  }
}

  static fromJS(data: any): GetAllPlanFeatureForEditQuery {
    const instance = new GetAllPlanFeatureForEditQuery();
    instance.init(data);
    return instance;
  }
}


