/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogLevel } from './log-level';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for GetAppLogsQuery */
export interface IGetAppLogsQuery {
  tenantId?: string;
  levels?: Array<LogLevel>;
  fromDate?: string;
  toDate?: string;
  userId?: string;
  search?: string;
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;
}

/** Class for GetAppLogsQuery */
export class GetAppLogsQuery implements IGetAppLogsQuery {
  tenantId?: string;
  levels?: Array<LogLevel>;
  fromDate?: string;
  toDate?: string;
  userId?: string;
  search?: string;
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: string;

  constructor(data?: IGetAppLogsQuery) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.tenantId = data["tenantId"];
    if (Array.isArray(data["levels"])) {
      this.levels = [] as any;
      for (let item of data["levels"])
        (this.levels as any).push(item);
    }
    this.fromDate = data["fromDate"];
    this.toDate = data["toDate"];
    this.userId = data["userId"];
    this.search = data["search"];
    this.pageNumber = data["pageNumber"];
    this.pageSize = data["pageSize"];
    this.sortBy = data["sortBy"];
    this.sortDirection = data["sortDirection"];
  }
}

  static fromJS(data: any): GetAppLogsQuery {
    const instance = new GetAppLogsQuery();
    instance.init(data);
    return instance;
  }
}


