/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for GetPageInfoQuery */
export interface IGetPageInfoQuery {
  pageId: string;
  culture: string;
}

/** Class for GetPageInfoQuery */
export class GetPageInfoQuery implements IGetPageInfoQuery {
  pageId!: string;
  culture!: string;

  constructor(data?: IGetPageInfoQuery) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.pageId = data["pageId"];
    this.culture = data["culture"];
  }
}

  static fromJS(data: any): GetPageInfoQuery {
    const instance = new GetPageInfoQuery();
    instance.init(data);
    return instance;
  }
}


