/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for GetProductAttributesQuery */
export interface IGetProductAttributesQuery {
  productTypeId?: string;
}

/** Class for GetProductAttributesQuery */
export class GetProductAttributesQuery implements IGetProductAttributesQuery {
  productTypeId?: string;

  constructor(data?: IGetProductAttributesQuery) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.productTypeId = data["productTypeId"];
  }
}

  static fromJS(data: any): GetProductAttributesQuery {
    const instance = new GetProductAttributesQuery();
    instance.init(data);
    return instance;
  }
}


