/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for GetTenantsAutoCompleteQuery */
export interface IGetTenantsAutoCompleteQuery {
  filter: string;
}

/** Class for GetTenantsAutoCompleteQuery */
export class GetTenantsAutoCompleteQuery implements IGetTenantsAutoCompleteQuery {
  filter!: string;

  constructor(data?: IGetTenantsAutoCompleteQuery) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.filter = data["filter"];
  }
}

  static fromJS(data: any): GetTenantsAutoCompleteQuery {
    const instance = new GetTenantsAutoCompleteQuery();
    instance.init(data);
    return instance;
  }
}


