/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for GetProductCategoryForEditQuery */
export interface IGetProductCategoryForEditQuery {
  id?: string;
}

/** Class for GetProductCategoryForEditQuery */
export class GetProductCategoryForEditQuery implements IGetProductCategoryForEditQuery {
  id?: string;

  constructor(data?: IGetProductCategoryForEditQuery) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
  }
}

  static fromJS(data: any): GetProductCategoryForEditQuery {
    const instance = new GetProductCategoryForEditQuery();
    instance.init(data);
    return instance;
  }
}


