/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for LanguageDTO */
export interface ILanguageDTO {
  culture?: string;
  name?: string;
  isRtl?: boolean;
  flag?: string;
  isDefault?: boolean;
  isActive?: boolean;
}

/** Class for LanguageDTO */
export class LanguageDTO implements ILanguageDTO {
  culture?: string;
  name?: string;
  isRtl?: boolean;
  flag?: string;
  isDefault?: boolean;
  isActive?: boolean;

  constructor(data?: ILanguageDTO) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.culture = data["culture"];
    this.name = data["name"];
    this.isRtl = data["isRtl"];
    this.flag = data["flag"];
    this.isDefault = data["isDefault"];
    this.isActive = data["isActive"];
  }
}

  static fromJS(data: any): LanguageDTO {
    const instance = new LanguageDTO();
    instance.init(data);
    return instance;
  }
}


