/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum LogSinkMask {

    None = 0,

    File = 1,

    Database = 2,

    Telegram = 4,

    Bale = 8,

    ExternalApi = 16,

    All = 31
}

