/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum MenuTargetEnum {

    Self = 0,

    Blank = 1,

    Parent = 2,

    Top = 3
}

