/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Meta { 
    TotalCount?: number | null;
    PageNumber?: number | null;
    PageSize?: number | null;
    readonly TotalPages?: number | null;
}

