/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageTypeEnum } from './page-type-enum';
import { PageStatusEnum } from './page-status-enum';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for PageDto */
export interface IPageDto {
  id?: string;
  slag?: string;
  status?: PageStatusEnum;
  author?: string;
  created?: string;
  title: string;
  introduction?: string;
  description?: string;
  type?: PageTypeEnum;
  isActive?: boolean;
  isSystem?: boolean;
  coverImage?: string;
  culture: string;
  metaDescription?: string;
  metaKeywords?: string;
  data?: string;
  styles?: string;
  scripts?: string;
  html?: string;
}

/** Class for PageDto */
export class PageDto implements IPageDto {
  id?: string;
  slag?: string;
  status?: PageStatusEnum;
  author?: string;
  created?: string;
  title!: string;
  introduction?: string;
  description?: string;
  type?: PageTypeEnum;
  isActive?: boolean;
  isSystem?: boolean;
  coverImage?: string;
  culture!: string;
  metaDescription?: string;
  metaKeywords?: string;
  data?: string;
  styles?: string;
  scripts?: string;
  html?: string;

  constructor(data?: IPageDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.slag = data["slag"];
    this.status = data["status"];
    this.author = data["author"];
    this.created = data["created"];
    this.title = data["title"];
    this.introduction = data["introduction"];
    this.description = data["description"];
    this.type = data["type"];
    this.isActive = data["isActive"];
    this.isSystem = data["isSystem"];
    this.coverImage = data["coverImage"];
    this.culture = data["culture"];
    this.metaDescription = data["metaDescription"];
    this.metaKeywords = data["metaKeywords"];
    this.data = data["data"];
    this.styles = data["styles"];
    this.scripts = data["scripts"];
    this.html = data["html"];
  }
}

  static fromJS(data: any): PageDto {
    const instance = new PageDto();
    instance.init(data);
    return instance;
  }
}


