/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum PageTypeEnum {

    OtherPages = 0,

    HomePage = 1,

    AboutUs = 2,

    ContactUs = 3,

    Blog = 4,

    Article = 5,

    News = 6
}

