/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanTranslationDto } from './plan-translation-dto';
import { BillingType } from './billing-type';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for PlanDto */
export interface IPlanDto {
  id?: string;
  title?: string;
  code: string;
  description?: string;
  billingType?: BillingType;
  isActive?: boolean;
  isPublic?: boolean;
  createdAt?: string;
  translations?: Array<PlanTranslationDto>;
}

/** Class for PlanDto */
export class PlanDto implements IPlanDto {
  id?: string;
  title?: string;
  code!: string;
  description?: string;
  billingType?: BillingType;
  isActive?: boolean;
  isPublic?: boolean;
  createdAt?: string;
  translations?: Array<PlanTranslationDto>;

  constructor(data?: IPlanDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.title = data["title"];
    this.code = data["code"];
    this.description = data["description"];
    this.billingType = data["billingType"];
    this.isActive = data["isActive"];
    this.isPublic = data["isPublic"];
    this.createdAt = data["createdAt"];
    if (Array.isArray(data["translations"])) {
      this.translations = [] as any;
      for (let item of data["translations"])
        (this.translations as any).push(PlanTranslationDto.fromJS(item));
    }
  }
}

  static fromJS(data: any): PlanDto {
    const instance = new PlanDto();
    instance.init(data);
    return instance;
  }
}


