/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for PlanFeatureTranslationDto */
export interface IPlanFeatureTranslationDto {
  planFeatureId?: string;
  culture: string;
  title?: string;
}

/** Class for PlanFeatureTranslationDto */
export class PlanFeatureTranslationDto implements IPlanFeatureTranslationDto {
  planFeatureId?: string;
  culture!: string;
  title?: string;

  constructor(data?: IPlanFeatureTranslationDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.planFeatureId = data["planFeatureId"];
    this.culture = data["culture"];
    this.title = data["title"];
  }
}

  static fromJS(data: any): PlanFeatureTranslationDto {
    const instance = new PlanFeatureTranslationDto();
    instance.init(data);
    return instance;
  }
}


