/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ProblemDetails */
export interface IProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
}

/** Class for ProblemDetails */
export class ProblemDetails implements IProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;

  constructor(data?: IProblemDetails) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.type = data["type"];
    this.title = data["title"];
    this.status = data["status"];
    this.detail = data["detail"];
    this.instance = data["instance"];
  }
}

  static fromJS(data: any): ProblemDetails {
    const instance = new ProblemDetails();
    instance.init(data);
    return instance;
  }
}


