/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for ProductCategoryTranslationDto */
export interface IProductCategoryTranslationDto {
  productCategoryId?: string;
  culture: string;
  title?: string;
  description?: string;
}

/** Class for ProductCategoryTranslationDto */
export class ProductCategoryTranslationDto implements IProductCategoryTranslationDto {
  productCategoryId?: string;
  culture!: string;
  title?: string;
  description?: string;

  constructor(data?: IProductCategoryTranslationDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.productCategoryId = data["productCategoryId"];
    this.culture = data["culture"];
    this.title = data["title"];
    this.description = data["description"];
  }
}

  static fromJS(data: any): ProductCategoryTranslationDto {
    const instance = new ProductCategoryTranslationDto();
    instance.init(data);
    return instance;
  }
}


