/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ProductTypeTranslationDto */
export interface IProductTypeTranslationDto {
  productTypeId?: string;
  culture: string;
  name: string;
  description?: string;
}

/** Class for ProductTypeTranslationDto */
export class ProductTypeTranslationDto implements IProductTypeTranslationDto {
  productTypeId?: string;
  culture!: string;
  name!: string;
  description?: string;

  constructor(data?: IProductTypeTranslationDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.productTypeId = data["productTypeId"];
    this.culture = data["culture"];
    this.name = data["name"];
    this.description = data["description"];
  }
}

  static fromJS(data: any): ProductTypeTranslationDto {
    const instance = new ProductTypeTranslationDto();
    instance.init(data);
    return instance;
  }
}


