/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Meta } from './meta';
import { ApiError } from './api-error';
import { ProductCategoryDto } from './product-category-dto';


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for ProductCategoryDtoListApiResponse */
export interface IProductCategoryDtoListApiResponse {
  success?: boolean;
  data?: Array<ProductCategoryDto>;
  errors?: Array<ApiError>;
  meta?: Meta;
}

/** Class for ProductCategoryDtoListApiResponse */
export class ProductCategoryDtoListApiResponse implements IProductCategoryDtoListApiResponse {
  success?: boolean;
  data?: Array<ProductCategoryDto>;
  errors?: Array<ApiError>;
  meta?: Meta;

  constructor(data?: IProductCategoryDtoListApiResponse) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.success = data["success"];
    if (Array.isArray(data["data"])) {
      this.data = [] as any;
      for (let item of data["data"])
        (this.data as any).push(ProductCategoryDto.fromJS(item));
    }
    if (Array.isArray(data["errors"])) {
      this.errors = [] as any;
      for (let item of data["errors"])
        (this.errors as any).push(ApiError.fromJS(item));
    }
    this.meta = data["meta"];
  }
}

  static fromJS(data: any): ProductCategoryDtoListApiResponse {
    const instance = new ProductCategoryDtoListApiResponse();
    instance.init(data);
    return instance;
  }
}


