/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ProvisioningStatus {

    NotStarted = 0,

    Creating = 1,

    Ready = 2,

    Failed = 3
}

