/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProvisioningStatusDto } from './provisioning-status-dto';
import { Meta } from './meta';
import { ApiError } from './api-error';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for ProvisioningStatusDtoApiResponse */
export interface IProvisioningStatusDtoApiResponse {
  success?: boolean;
  data?: ProvisioningStatusDto;
  errors?: Array<ApiError>;
  meta?: Meta;
}

/** Class for ProvisioningStatusDtoApiResponse */
export class ProvisioningStatusDtoApiResponse implements IProvisioningStatusDtoApiResponse {
  success?: boolean;
  data?: ProvisioningStatusDto;
  errors?: Array<ApiError>;
  meta?: Meta;

  constructor(data?: IProvisioningStatusDtoApiResponse) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.success = data["success"];
    this.data = data["data"];
    if (Array.isArray(data["errors"])) {
      this.errors = [] as any;
      for (let item of data["errors"])
        (this.errors as any).push(ApiError.fromJS(item));
    }
    this.meta = data["meta"];
  }
}

  static fromJS(data: any): ProvisioningStatusDtoApiResponse {
    const instance = new ProvisioningStatusDtoApiResponse();
    instance.init(data);
    return instance;
  }
}


