/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDTO } from './role-dto';
import { Meta } from './meta';
import { ApiError } from './api-error';


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for RoleDTOApiResponse */
export interface IRoleDTOApiResponse {
  success?: boolean;
  data?: RoleDTO;
  errors?: Array<ApiError>;
  meta?: Meta;
}

/** Class for RoleDTOApiResponse */
export class RoleDTOApiResponse implements IRoleDTOApiResponse {
  success?: boolean;
  data?: RoleDTO;
  errors?: Array<ApiError>;
  meta?: Meta;

  constructor(data?: IRoleDTOApiResponse) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.success = data["success"];
    this.data = data["data"];
    if (Array.isArray(data["errors"])) {
      this.errors = [] as any;
      for (let item of data["errors"])
        (this.errors as any).push(ApiError.fromJS(item));
    }
    this.meta = data["meta"];
  }
}

  static fromJS(data: any): RoleDTOApiResponse {
    const instance = new RoleDTOApiResponse();
    instance.init(data);
    return instance;
  }
}


