/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleResponseDTO } from './role-response-dto';
import { Meta } from './meta';
import { ApiError } from './api-error';


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/*Created with custom template*/
export class RoleResponseDTOApiResponse {
Success?: boolean;
  
Data?: RoleResponseDTO;
  
Errors?: Array<ApiError>;
  
Meta?: Meta;
  
}

