/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for TenantDatabaseDto */
export interface ITenantDatabaseDto {
  tenantId: string;
  server: string;
  databaseName: string;
  lastConnectionTest: string;
  isConnectionHealthy: boolean;
}

/** Class for TenantDatabaseDto */
export class TenantDatabaseDto implements ITenantDatabaseDto {
  tenantId!: string;
  server!: string;
  databaseName!: string;
  lastConnectionTest!: string;
  isConnectionHealthy!: boolean;

  constructor(data?: ITenantDatabaseDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.tenantId = data["tenantId"];
    this.server = data["server"];
    this.databaseName = data["databaseName"];
    this.lastConnectionTest = data["lastConnectionTest"];
    this.isConnectionHealthy = data["isConnectionHealthy"];
  }
}

  static fromJS(data: any): TenantDatabaseDto {
    const instance = new TenantDatabaseDto();
    instance.init(data);
    return instance;
  }
}


