/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationDto } from './notification-dto';


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for UnReadNotificationListDto */
export interface IUnReadNotificationListDto {
  unreadCount?: number;
  items?: Array<NotificationDto>;
}

/** Class for UnReadNotificationListDto */
export class UnReadNotificationListDto implements IUnReadNotificationListDto {
  unreadCount?: number;
  items?: Array<NotificationDto>;

  constructor(data?: IUnReadNotificationListDto) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.unreadCount = data["unreadCount"];
    if (Array.isArray(data["items"])) {
      this.items = [] as any;
      for (let item of data["items"])
        (this.items as any).push(NotificationDto.fromJS(item));
    }
  }
}

  static fromJS(data: any): UnReadNotificationListDto {
    const instance = new UnReadNotificationListDto();
    instance.init(data);
    return instance;
  }
}


