/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* Created with custom template */

/** Interface for UpdatePageCommand */
export interface IUpdatePageCommand {
  pageId?: string;
  culture?: string;
  title?: string;
  _abstract?: string;
  description?: string;
  html?: string;
  styles?: string;
  scripts?: string;
  lastModifiedBy?: string;
}

/** Class for UpdatePageCommand */
export class UpdatePageCommand implements IUpdatePageCommand {
  pageId?: string;
  culture?: string;
  title?: string;
  _abstract?: string;
  description?: string;
  html?: string;
  styles?: string;
  scripts?: string;
  lastModifiedBy?: string;

  constructor(data?: IUpdatePageCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.pageId = data["pageId"];
    this.culture = data["culture"];
    this.title = data["title"];
    this._abstract = data["abstract"];
    this.description = data["description"];
    this.html = data["html"];
    this.styles = data["styles"];
    this.scripts = data["scripts"];
    this.lastModifiedBy = data["lastModifiedBy"];
  }
}

  static fromJS(data: any): UpdatePageCommand {
    const instance = new UpdatePageCommand();
    instance.init(data);
    return instance;
  }
}


