/**
 * SamaniCrm.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/* Created with custom template by mohammadreza SAMANI*/

/** Interface for UpdateTenantCommand */
export interface IUpdateTenantCommand {
  id: string;
  name: string;
  logo: string;
  primaryColor: string;
}

/** Class for UpdateTenantCommand */
export class UpdateTenantCommand implements IUpdateTenantCommand {
  id!: string;
  name!: string;
  logo!: string;
  primaryColor!: string;

  constructor(data?: IUpdateTenantCommand) {
    if (data) {
      for (let property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

init(data?: any) {
  if (data) {
    this.id = data["id"];
    this.name = data["name"];
    this.logo = data["logo"];
    this.primaryColor = data["primaryColor"];
  }
}

  static fromJS(data: any): UpdateTenantCommand {
    const instance = new UpdateTenantCommand();
    instance.init(data);
    return instance;
  }
}


