/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserResponseDTO { 
    Id: string;
    UserName?: string | null;
    FirstName?: string | null;
    LastName?: string | null;
    FullName?: string | null;
    Email?: string | null;
    ProfilePicture?: string | null;
}

