/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDetailsResponseDTO { 
    Id?: string;
    FullName?: string | null;
    UserName?: string | null;
    Email?: string | null;
    Roles?: Array<string> | null;
}

