const ICON_MAP = {
  backgroundColor: 'fa-fill-drip',
  backgroundImage: 'fa-image',
  backgroundSize: 'fa-expand',
  backgroundPosition: 'fa-crosshairs',
  backgroundRepeat: 'fa-redo',
  backgroundAttachment: 'fa-paperclip',
  backgroundBlend: 'fa-adjust',

  padding: 'fa-arrows-alt',
  margin: 'fa-arrows-alt-h',
  gap: 'fa-border-all',

  border: 'fa-border-style',
  borderTop: 'fa-border-top',
  borderRight: 'fa-border-right',
  borderBottom: 'fa-border-bottom',
  borderLeft: 'fa-border-left',
  borderWidth: 'fa-weight-hanging',
  borderStyle: 'fa-ellipsis-h',
  borderColor: 'fa-tint',
  borderRadius: 'fa-circle-notch',
  outline: 'fa-shapes',
  outlineColor: 'fa-tint',
  outlineWidth: 'fa-weight-hanging',

  boxShadow: 'fa-layer-group',
  textShadow: 'fa-layer-group',
  dropShadow: 'fa-cloud-showers-heavy',

  color: 'fa-palette',
  fontSize: 'fa-text-height',
  fontFamily: 'fa-font',
  fontWeight: 'fa-weight',
  fontStyle: 'fa-italic',
  textTransform: 'fa-text-case',
  letterSpacing: 'fa-text-width',
  lineHeight: 'fa-arrows-alt-v',
  textAlign: 'fa-align-center',
  textDecoration: 'fa-underline',
  direction: 'fa-code-branch',

  opacity: 'fa-eye-low-vision',
  transform: 'fa-sync-alt',
  transition: 'fa-wave-square',
  animation: 'fa-play-circle',
  blendMode: 'fa-object-group',
  filter: 'fa-filter',

  width: 'fa-arrows-alt-h',
  height: 'fa-arrows-alt-v',
  minWidth: 'fa-arrow-alt-circle-right',
  maxWidth: 'fa-arrow-alt-circle-left',
  position: 'fa-map-marker-alt',
  top: 'fa-arrows',
  right: 'fa-arrows',
  bottom: 'fa-arrows',
  left: 'fa-arrows',
  zIndex: 'fa-layer-group',
  display: 'fa-desktop',
  flexDirection: 'fa-align-justify',
  alignItems: 'fa-arrows-alt-v',
  justifyContent: 'fa-arrows-alt-h',
  overflow: 'fa-expand-arrows-alt',
  visibility: 'fa-eye',

  cursor: 'fa-mouse-pointer',
  pointerEvents: 'fa-hand-paper',
  userSelect: 'fa-user-check',
  pseudoStates: 'fa-mouse',

  responsiveMobile: 'fa-mobile-alt',
  responsiveTablet: 'fa-tablet-alt',
  responsiveDesktop: 'fa-desktop',
};
