export * from './account.service';
import { AccountServiceProxy } from './account.service';
export * from './captcha.service';
import { CaptchaServiceProxy } from './captcha.service';
export * from './common.service';
import { CommonServiceProxy } from './common.service';
export * from './dasboard.service';
import { DasboardServiceProxy } from './dasboard.service';
export * from './external-auth.service';
import { ExternalAuthServiceProxy } from './external-auth.service';
export * from './external-providers.service';
import { ExternalProvidersServiceProxy } from './external-providers.service';
export * from './file-manager.service';
import { FileManagerServiceProxy } from './file-manager.service';
export * from './file-serve.service';
import { FileServeServiceProxy } from './file-serve.service';
export * from './language.service';
import { LanguageServiceProxy } from './language.service';
export * from './maintenance.service';
import { MaintenanceServiceProxy } from './maintenance.service';
export * from './menu.service';
import { MenuServiceProxy } from './menu.service';
export * from './notification.service';
import { NotificationServiceProxy } from './notification.service';
export * from './page-builder.service';
import { PageBuilderServiceProxy } from './page-builder.service';
export * from './pages.service';
import { PagesServiceProxy } from './pages.service';
export * from './product.service';
import { ProductServiceProxy } from './product.service';
export * from './public.service';
import { PublicServiceProxy } from './public.service';
export * from './role.service';
import { RoleServiceProxy } from './role.service';
export * from './security-settings.service';
import { SecuritySettingsServiceProxy } from './security-settings.service';
export * from './user.service';
import { UserServiceProxy } from './user.service';
export * from './weather-forecast.service';
import { WeatherForecastServiceProxy } from './weather-forecast.service';
export const APIS = [AccountServiceProxy, CaptchaServiceProxy, CommonServiceProxy, DasboardServiceProxy, ExternalAuthServiceProxy, ExternalProvidersServiceProxy, FileManagerServiceProxy, FileServeServiceProxy, LanguageServiceProxy, MaintenanceServiceProxy, MenuServiceProxy, NotificationServiceProxy, PageBuilderServiceProxy, PagesServiceProxy, ProductServiceProxy, PublicServiceProxy, RoleServiceProxy, SecuritySettingsServiceProxy, UserServiceProxy, WeatherForecastServiceProxy];
