export * from './account.service';
import { AccountServiceProxy } from './account.service';
export * from './captcha.service';
import { CaptchaServiceProxy } from './captcha.service';
export * from './common.service';
import { CommonServiceProxy } from './common.service';
export * from './language.service';
import { LanguageServiceProxy } from './language.service';
export * from './maintenance.service';
import { MaintenanceServiceProxy } from './maintenance.service';
export * from './menu.service';
import { MenuServiceProxy } from './menu.service';
export * from './role.service';
import { RoleServiceProxy } from './role.service';
export * from './security-settings.service';
import { SecuritySettingsServiceProxy } from './security-settings.service';
export * from './user.service';
import { UserServiceProxy } from './user.service';
export * from './weather-forecast.service';
import { WeatherForecastServiceProxy } from './weather-forecast.service';
export const APIS = [AccountServiceProxy, CaptchaServiceProxy, CommonServiceProxy, LanguageServiceProxy, MaintenanceServiceProxy, MenuServiceProxy, RoleServiceProxy, SecuritySettingsServiceProxy, UserServiceProxy, WeatherForecastServiceProxy];
