/**
 * SamaniCrm API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Int32ApiResponse } from '../model/models';
import { RoleCreateCommand } from '../model/models';
import { RoleResponseDTOApiResponse } from '../model/models';
import { RoleResponseDTOListApiResponse } from '../model/models';
import { UpdateRoleCommand } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoleServiceProxyInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param roleCreateCommand 
     */
    createRole(roleCreateCommand?: RoleCreateCommand, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param id 
     */
    deleteRole(id: string, extraHttpRequestParams?: any): Observable<Int32ApiResponse>;

    /**
     * 
     * 
     * @param id 
     * @param updateRoleCommand 
     */
    editRole(id: string, updateRoleCommand?: UpdateRoleCommand, extraHttpRequestParams?: any): Observable<Int32ApiResponse>;

    /**
     * 
     * 
     */
    getRole(extraHttpRequestParams?: any): Observable<RoleResponseDTOListApiResponse>;

    /**
     * 
     * 
     * @param id 
     */
    getRoleById(id: string, extraHttpRequestParams?: any): Observable<RoleResponseDTOApiResponse>;

}
